# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aviato' do
  pod 'SnapKit'
  pod 'CryptoSwift'
  pod 'Alamofire'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aviato

end
